// components/Layout.tsx
import Head from 'next/head';
import React, { ReactNode, useEffect } from "react";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { useDispatch } from "react-redux";
import Header from "./Header";
import Footer from "./Footer";
import { setCart, setWishlist } from "../features/productSlice";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  const dispatch = useDispatch();

  // Load wishlist and cart from local storage on component mount
  useEffect(() => {
    const storedWishlist = localStorage.getItem("wishlist");
    if (storedWishlist) {
      dispatch(setWishlist(JSON.parse(storedWishlist)));
    }

    const storedCart = localStorage.getItem("cart");
    if (storedCart) {
      dispatch(setCart(JSON.parse(storedCart)));
    }
  }, [dispatch]);

  return (
    <div className={montserrat.className}>
      <Head>
        <title>Next Basket - Ecommerce Website</title>
        <meta name="description" content="Checkout our cool page" key="desc" />
        <meta property="og:title" content="Social Title for Cool Page" />
        <meta
          property="og:description"
          content="And a social description for our cool page"
        />
        <meta
          property="og:image"
          content="https://example.com/images/cool-page.jpg"
        />
      </Head>
      <Header />
      <main className="">{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
