// components/Layout.tsx
import Head from "next/head";
import React, { ReactNode, useEffect } from "react";
import type { Metadata } from "next";
import { useDispatch } from "react-redux";
import Header from "./Header";
import Sidebar from "./Sidebar";

import { Open_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});
const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className={openSans.className}>
      <Head>
        <title>Medida Project</title>
        <meta name="description" content="Checkout our cool page" key="desc" />
        <meta property="og:title" content="Social Title for Cool Page" />
        <meta
          property="og:description"
          content="And a social description for our cool page"
        />
        <meta
          property="og:image"
          content="https://example.com/images/cool-page.jpg"
        />
      </Head>

      <div className="flex h-screen bg-gray-50">
        <Sidebar />
        <div className="flex-1 flex flex-col overflow-hidden">
          <Header />
          <main className="flex-1 overflow-x-hidden overflow-y-auto bg-gray-50 p-4 md:p-6">
            {children}
          </main>
        </div>
      </div>
    </div>
  );
};

export default Layout;
